### ISSUE TITLE
Mobile Meta Tag

### ISSUE THREAD

**Issue by Mikeysax** [dreshfield/splurty#1]
On mobile things don't look as good as they could be.
One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.
Let me know in the comments once you figured that step out :)

**Comment by dreshfield** [comment]
@Mikeysax Thanks for letting me know! https://github.com/dreshfield/splurty/commit/67971c5374f614822db4befa0ab65d9bfb480e5b seems to have largely solved the responsive issue, though some elements of the header and footer still seem a little out of whack.

**Comment by Mikeysax** [comment]
:+1: 

I would keep going with the other tracks and come back another time to fix the small visual issues.
